# Generated by Django 4.2.15 on 2024-11-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lines_of_code", models.IntegerField()),
                ("username", models.CharField(max_length=100)),
                ("repositories", models.JSONField()),
                ("date_requested", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
