# Generated by Django 4.2.15 on 2024-11-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrecord",
            name="lines_of_code_per_language",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
